name: Linting

on:
  push:
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ ninja-build

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect --force
          pip install clang-format==21.*

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Configure, Lint, and Format
        run: |
          make lint
          make format-check
